name = "logging"
version = "1.0.0"
maintainer = "davidpfister"
author = "davidpfister"
description = "Simple logging library"
categories = ["general"]
keywords = ["info", "debug", "fatal", "error", "warn", "debug"]
homepage = "https://github.com/davidpfister/"


[build]
auto-tests = false

[library]
include-dir = "include"

[preprocess]
cpp.suffixes = ["F90", "f90"]
cpp.macros = ["_WIN32", "_FPM"]

[[test]]
name       = "test_log"
source-dir = "tests"