name = "assertion"
version = "1.0.0"
maintainer = "davidpfister"
author = "davidpfister"
description = "Simple assertion methods for unit testing"
categories = ["unit tests"]
keywords = ["assertion", "test"]
homepage = "https://github.com/davidpfister/"


[build]
auto-tests = false

[library]
include-dir = "include"

[preprocess]
cpp.suffixes = ["F90", "f90"]
cpp.macros = ["_FPM"]

[[test]]
name       = "test_assertion"
source-dir = "tests"