name = "namelist"
version = "1.0.0"
maintainer = "davidpfister"
author = "davidpfister"
description = "Namelist serialization and deserialization"
categories = ["general"]
keywords = ["namelist", "serialization", "deserialization"]
homepage = "https://github.com/davidpfister/fortiche"


[build]
auto-tests = false

[library]
include-dir = "include"

[preprocess]
cpp.suffixes = ["F90", "f90"]
cpp.macros = ["_FPM"]

[[test]]
name       = "test_optional"
source-dir = "tests"