name = "contract"
version = "1.0.0"
maintainer = "davidpfister"
author = "davidpfister"
description = "Implements contract based inheritance and multiple inheritance"
categories = ["general"]
keywords = ["oop", "inheritance"]
homepage = "https://github.com/davidpfister/fortiche"


[build]
auto-tests = false

[library]
include-dir = "include"

[preprocess]
cpp.suffixes = ["F90", "f90"]
cpp.macros = ["_FPM"]

[[test]]
name       = "test_contract"
source-dir = "tests"