name = "assert_f"
version = "1.0.0"
maintainer = "davidpfister"
author = "davidpfister"
description = "Simple assertion methods for unit testing"
categories = ["unit tests"]
keywords = ["assert", "test"]
homepage = "https://github.com/davidpfister/assert.f"


[build]
auto-tests = false

[library]
include-dir = "include"

[preprocess]
cpp.suffixes = ["F90", "f90"]
cpp.macros = ["_WIN32", "_FPM"]

[[test]]
name       = "test_assert"
source-dir = "tests"