name = "array"
version = "1.0.0"
maintainer = "davidpfister"
author = "davidpfister"
description = "Add reallocate and risize to fortran keywords"
categories = ["general"]
keywords = ["resize", "reallocate"]
homepage = "https://github.com/davidpfister/fortiche"


[build]
auto-tests = false

[library]
include-dir = "include"

[preprocess]
cpp.suffixes = ["F90", "f90"]
cpp.macros = ["_FPM"]

[[test]]
name       = "test_array"
source-dir = "tests"