name = "logical"
version = "1.0.0"
maintainer = "davidpfister"
author = "davidpfister"
description = "Add simple short-circuit mechanism to 'if' block"
categories = ["general"]
keywords = ["if", "short-circuit"]
homepage = "https://github.com/davidpfister/"


[build]
auto-tests = false

[library]
include-dir = "include"

[preprocess]
cpp.suffixes = ["F90", "f90"]
cpp.macros = ["_FPM"]

[[test]]
name       = "test_logical"
source-dir = "tests"