name = "app"
version = "1.0.0"
maintainer = "davidpfister"
author = "davidpfister"
description = "Application framework using preprocessing"
categories = ["general"]
keywords = ["app", "preprocessing"]
homepage = "https://github.com/davidpfister/fortiche"


[build]
auto-tests = false

[library]
include-dir = "include"

[preprocess]
cpp.suffixes = ["F90", "f90"]
cpp.macros = ["_WIN32", "_FPM"]

[[test]]
name       = "test_app"
source-dir = "tests"